using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;

namespace HomeMcp.Server.Api;

/// <summary>
/// External-facing REST endpoint for one-time device pairing.
/// Accessible by client devices before they establish a gRPC connection.
/// Versioned (/api/v1/) because external clients depend on this contract.
/// </summary>
[ApiController]
[Route("api/v1")]
[Microsoft.AspNetCore.Cors.EnableCors("clients")]
public sealed class PairingController : ControllerBase
{
    // TODO (v1): require a PIN generated by admin UI; validate against in-memory store.
    // TODO (v1): persist device via IDeviceRepository with argon2-hashed token.
    [HttpPost("pair")]
    public IActionResult Pair([FromBody] PairRequest req)
    {
        var deviceId = Guid.CreateVersion7().ToString("N");
        var token = Convert.ToBase64String(RandomNumberGenerator.GetBytes(32));

        return Ok(new PairResponse(deviceId, token));
    }
}

public sealed record PairRequest(
    string? Pin,
    string? Locale,
    PairCapabilities? Capabilities);

public sealed record PairCapabilities(
    bool Stt,
    bool Tts,
    bool AudioPlayback,
    bool MediaPlayer,
    bool Display);

public sealed record PairResponse(
    string DeviceId,
    string DeviceToken);
